### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by rohimma** [sanathp/statusok#19]
Hello,

when i set the statusOk program running, i get a lot off the following errors:  
`dial tcp <hostip>: i/o timeout` & `net/http: TLS handshake timeout`

i have looked around and most of the results are about DNS and / or Networking but both seem to be fine..  
do you have a tip for where to look to solve this error?

**Comment by sanathp** [comment]
Might be some problem with your internet connection ? I cant think of any other reason for now

**Comment by rohimma** [comment]
oke, seems to work better now.. (didn't change a thing)

i will look in to the internet connection.
