### ISSUE TITLE
statusok exits after receiving 500 response.  

### ISSUE THREAD

**Issue by daya0576** [sanathp/statusok#22]
Hi,

The program exits immediately after receiving a 500 response. 
How can statusok send me an alert email and keep monitoring the other apis? 

![image](https://user-images.githubusercontent.com/6239652/32593459-9f16096e-c4ed-11e7-9a5f-36f1254bc4af.png)

**Comment by sanathp** [comment]
On Launch, StatusOk will check all the apis mentioned in config.json file. If the response code is not same as expected response code it will not start monitoring. This is to make sure all the apis are working as expected atleast at the start.

**Comment by daya0576** [comment]
Got it. 
Thank u so much.
