### ISSUE TITLE
Tries to initialise dingding even if no config is provided for it

### ISSUE THREAD

**Issue by saward** [sanathp/statusok#35]
As per subject.  My config only has slack in it, yet it tries to initialise dingding and has an error.

**Comment by rmorrison61** [comment]
I had the same issue, it appears that this problem was tied to the Data structure for the Dingding notification service.  I just put through a pull request, which resolved the issue for me: https://github.com/sanathp/statusok/pull/41

CC: @sanathp

**Comment by sanathp** [comment]
Fixed with this [commit](https://github.com/sanathp/statusok/commit/da193355eece3c8f87b8d055cb223dae197bd594) . Will publish in next release.
