### ISSUE TITLE
Mailgun Notification service is breaking the install/build

### ISSUE THREAD

**Issue by rmorrison61** [sanathp/statusok#42]
When trying to install/build there was an error with the MailGun notification service.  After reviewing, it looks like the Mailgun service no longer requires a public key to be passed (just domain and private key).  I put through a pull request that adheres to the new requirements of the Mailgun v2 API: https://github.com/sanathp/statusok/pull/40

**Comment by Artanicus** [comment]
The pull request doesn't seem to be enough, at least not anymore:
```
# github.com/sanathp/statusok/notify
notify/mailgun_notify.go:46:40: not enough arguments in call to mailGunClient.Send
        have (*mailgun.Message)
        want (context.Context, *mailgun.Message)
notify/mailgun_notify.go:61:40: not enough arguments in call to mailGunClient.Send
        have (*mailgun.Message)
        want (context.Context, *mailgun.Message)
```

**Comment by sanathp** [comment]
Fixed with this [import change ](https://github.com/sanathp/statusok/commit/da193355eece3c8f87b8d055cb223dae197bd594)
